IMAGE_HEIGHT = 299
IMAGE_WIDTH = 299

CLASSES_NAMES = ["GermanShepherd", "Others"]
OTHER_CLASS = 'Others'

DATA_PATH = 'Data'
ORIGIN_DATA_PATH = DATA_PATH + '/origin'
DATASET_PATH = DATA_PATH + '/dataset'

BATCH_SIZE = 3